### ISSUE TITLE
Running multi-classification problem failed

### ISSUE THREAD

**Issue by redcican** [easyautoml/easyml#8]
I tried to test 'iris.csv', a simple multi-classes problem, but the code threw this error:

```
[2022-04-12 10:44:32,283: ERROR/MainProcess]    Warning: Exception caused ExtraTreesGini_BAG_L1 to fail during training... Skipping this model.       
[2022-04-12 10:44:32,284: ERROR/MainProcess]    
        Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].
[2022-04-12 10:44:32,285: ERROR/MainProcess] Detailed Traceback:
Traceback (most recent call last):
  File "_catboost.pyx", line 1249, in _catboost._MetricEval
  File "d:\python\easyml\env\lib\site-packages\autogluon\tabular\models\catboost\catboost_utils.py", line 68, in evaluate
    score = self.metric(np.array(target), y_pred) 
  File "d:\python\easyml\env\lib\site-packages\autogluon\core\metrics\__init__.py", line 127, in __call__
    return self._sign * self._score_func(y_true, y_pred,
  File "d:\python\easyml\env\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f    
    return f(*args, **kwargs)
  File "d:\python\easyml\env\lib\site-packages\sklearn\metrics\_classification.py", line 1071, in f1_score
    return fbeta_score(y_true, y_pred, beta=1, labels=labels,
  File "d:\python\easyml\env\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f    
    return f(*args, **kwargs)
  File "d:\python\easyml\env\lib\site-packages\sklearn\metrics\_classification.py", line 1195, in fbeta_score
    _, _, f, _ = precision_recall_fscore_support(y_true, y_pred,
  File "d:\python\easyml\env\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f    
    return f(*args, **kwargs)
  File "d:\python\easyml\env\lib\site-packages\sklearn\metrics\_classification.py", line 1464, in precision_recall_fscore_support
    labels = _check_set_wise_labels(y_true, y_pred, average, labels,
  File "d:\python\easyml\env\lib\site-packages\sklearn\metrics\_classification.py", line 1294, in _check_set_wise_labels
    raise ValueError("Target is %s but average='binary'. Please "
ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].
```

**Comment by redcican** [comment]
sovled by merged.
